"""remove customer from invoice

Revision ID: 278bd0419885
Revises: 1d96928d2cb3
Create Date: 2025-11-08 21:15:57.594463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278bd0419885'
down_revision = '1d96928d2cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
