"""fix invoice detail

Revision ID: 47d5cffefbc4
Revises: c6f565d06526
Create Date: 2025-11-09 00:45:59.376578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d5cffefbc4'
down_revision = 'c6f565d06526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_detail', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
