"""fix invoice detail

Revision ID: c6f565d06526
Revises: 278bd0419885
Create Date: 2025-11-09 00:13:14.652425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6f565d06526'
down_revision = '278bd0419885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_detail', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###
