"""Add profile on Product

Revision ID: ca1405a9ccce
Revises: 12c84a2cab46
Create Date: 2025-11-08 09:41:17.455231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca1405a9ccce'
down_revision = '12c84a2cab46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('profile')

    # ### end Alembic commands ###
